# Generated by Django 3.2.5 on 2023-04-02 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20230402_1301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='heighestBid',
            new_name='heighest_bid',
        ),
    ]
